/**
 * Addresses a client-built page may not take.
 *
 * THE FAILURE THIS PREVENTS IS SILENT, which is why it gets its own module and
 * its own check rather than a regex in a save action.
 *
 * Next resolves static route segments before dynamic ones. So a custom page
 * given the slug `faqs` saves cleanly, appears in the admin as published and
 * live, and is never served — every request for /faqs keeps hitting the
 * hand-written FAQ page. No error is raised anywhere, on either side. The
 * client would be looking at a page they had built, told it was live, and be
 * unable to find it.
 *
 * Deliberately free of imports so the save action, the dynamic route and the
 * check script can all share one list. A second copy of this list is how one of
 * them comes to be missing an entry.
 */

/**
 * The eight built-in pages, by their first path segment.
 *
 * Written out rather than derived from `PAGE_PATHS`, and the duplication is the
 * point: this list must also contain segments that are NOT pages — /admin, /api
 * — so deriving half of it and hand-writing the rest would hide which half was
 * which. `check:custom-pages` asserts the built-in half stays in step.
 */
export const BUILT_IN_PAGES = [
  "auction-info",
  "auction-items",
  "auction-planner",
  "auctioneers",
  "contact",
  "faqs",
  "testimonials",
] as const;

/** Route segments the application owns. */
const APPLICATION = [
  "admin",
  "api",
  // Shareable document links, /d/<slug>.
  "d",
] as const;

/**
 * Files and conventions served from the root.
 *
 * `_next` is the build output. The metadata files are real routes generated by
 * app/robots.ts, app/sitemap.ts and Next's own conventions — a page slugged
 * `sitemap.xml` would be shadowed exactly like `faqs` would.
 */
const WELL_KNOWN = [
  "_next",
  "favicon.ico",
  "robots.txt",
  "sitemap.xml",
  "opensearch.xml",
  "manifest.json",
  "sw.js",
  ".well-known",
] as const;

/**
 * Words that are not taken today but would be painful to have taken later.
 *
 * A slug is effectively permanent once it has been shared, so the cost of
 * reserving a word now is that somebody picks a different one, and the cost of
 * not reserving it is a page that has to be broken to add a feature.
 */
const RESERVED = [
  "search",
  "login",
  "logout",
  "signin",
  "signup",
  "account",
  "settings",
  "preview",
  "draft",
  "assets",
  "images",
  "static",
  "public",
] as const;

const TAKEN = new Set<string>([
  ...BUILT_IN_PAGES,
  ...APPLICATION,
  ...WELL_KNOWN,
  ...RESERVED,
]);

/** A slug that is well-formed: lowercase, hyphenated, no leading or trailing hyphen. */
const SHAPE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

export type SlugProblem =
  | { ok: true }
  | { ok: false; reason: string };

/**
 * Whether `slug` may be used for a client-built page.
 *
 * Returns the reason rather than a boolean, because every caller has to show it
 * to somebody — a form that says only "invalid" for eight different causes is a
 * form people guess at.
 */
export function checkSlug(slug: string, takenBy: Iterable<string> = []): SlugProblem {
  if (!slug) return { ok: false, reason: "Give the page an address." };

  if (slug.length > 60) {
    return { ok: false, reason: "That address is too long — keep it under 60 characters." };
  }

  if (!SHAPE.test(slug)) {
    return {
      ok: false,
      reason:
        "Use lowercase letters, numbers and hyphens only — like " +
        "“spring-gala”. No spaces, slashes or capitals.",
    };
  }

  if (TAKEN.has(slug)) {
    return {
      ok: false,
      reason:
        `“/${slug}” already belongs to the site itself, so a page there ` +
        "would never be shown. Pick another address.",
    };
  }

  for (const other of takenBy) {
    if (other === slug) {
      return { ok: false, reason: "Another page already uses that address." };
    }
  }

  return { ok: true };
}

/** Whether a request path could ever be a custom page. Used by the dynamic route. */
export function couldBeCustomPage(slug: string): boolean {
  return SHAPE.test(slug) && !TAKEN.has(slug) && slug.length <= 60;
}
